#!/bin/bash

# Read .env file and convert to -e arguments
env_vars=$(cat .env | tr '\n' ' ')
env_vars=${env_vars// / -e }

docker run -e $env_vars -it --rm -p 9000:9000 --name passport-api-rs passport-api-rs